### ISSUE TITLE
No rendering of references or values

### ISSUE THREAD

**Issue by joric** [gregdavill/kicadScripts#12]
No silk for resistors here: https://github.com/joric/nrfmicro/tree/devel
Image: https://i.imgur.com/IiW58gu.jpg
Maybe you could figure why faster than me.
Also PCB outline is wrong but that's probably should be another issue.
Kicad (5.1.5)-3
Inkscape 0.92.5 (I also had to comment out version check as there's no `--export-type=png` in the 0.92 anymore but it also totally doesn't work with 1.0 beta (1.0 just doesn't rasterize anything).
plot_board.py
```diff
- if len(version) > 1 and version[1] < "0.9":
+ if True:
```
Also I had to copy _pcbnew.pyd to the scripts directory. Also import _pcbnew try/catch block hides the message about ` ImportError: DLL load failed: The specified procedure could not be found`.

**Comment by gregdavill** [comment]
By default I don't think it renders references or values.

Try changing these lines here: https://github.com/gregdavill/kicadScripts/blob/master/plot_board.py#L417
```diff
- popt.SetPlotReference(False)
+ popt.SetPlotReference(True)
- popt.SetPlotValue(False)
+ popt.SetPlotValue(True)
```

**Comment by joric** [comment]
Cool thanks it works now. What about cutting the board outline with edge cuts would that be a problem? It's just always rectangular now. You can close this one. Maybe enable plotting reference values by default (if only it checks for the visiblity flags).

**Comment by gregdavill** [comment]
Cool.

I'm not sure there is an easy way with the current method of rendering to cut out board shapes. I think We'd have to manually create a filled polygon that is filled, that would replace the background. But there are some tricky edge cases to handle:
- Multiple islands
- Internal cutouts defined by `edge.cuts`

If you have an idea on implementation I'd be happy to look it over and merge it.
Initially this script was really just designed to create textures that can be used in Blender/Fusion360, where they will clip out parts of the image that extend over the boards geometry.

Alright I'll close this.
