### ISSUE TITLE
PCBNew not found, are you using KiCAD included Python ? 

### ISSUE THREAD

**Issue by yahio61** [gregdavill/kicadScripts#13]
Hello i see "PCBNew not found, are you using KiCAD included Python ?" error. i am using kicad  (5.1.5)-3, release build. what can ı do? Thanks

**Comment by gregdavill** [comment]
What platform are you trying to run on?

**Comment by yahio61** [comment]
windows 10

**Comment by gregdavill** [comment]
Are you using the included python?

`C:\Program Files\KiCad\Bin\python.exe plot_pcb.py <board.kicad_pcb>`

**Comment by yahio61** [comment]
ok thanks.
