### ISSUE TITLE
Failed on Rasterizing

### ISSUE THREAD

**Issue by metropt** [gregdavill/kicadScripts#7]
Hi,
I'm using kicad 5.1.4 and a recent clone of your scripts. Inkscape is 0.92.

It happens with any kicad project. If you need any more info feel free to ask.

Thank you

```
Merging layers...
Rasterizing...

** (inkscape:32483): WARNING **: 15:26:36.720: Cannot parse export area '438.269521221:438.534051221:699.209478779:552.093008779'; use 'x0:y0:x1:y1'. Nothing exported.
Traceback (most recent call last):
  File "../kicadScripts/plot_board.py", line 420, in <module>
    render(plot_plan, project_name + '-Front.png')
  File "../kicadScripts/plot_board.py", line 355, in render
    final_svg,
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['inkscape', '--export-area=438.269521221:438.534051221:699.209478779:552.093008779', '--export-dpi=1200', '--export-png', '/home/ze/development/pcb/plot/pcb-Front.png', '--export-background', '#998060', '/home/ze/development/pcb/plot/temp/pcb-merged.svg']' returned non-zero exit status 1.

```

**Comment by gregdavill** [comment]
Can you open "/home/ze/development/pcb/plot/temp/pcb-merged.svg" with inkscape directly?

**Comment by metropt** [comment]
Yes, inkscape can open the svg

**Comment by metropt** [comment]
I'm using Python 3.7.3

**Comment by josephpal** [comment]
@metropt Maybe you wanna take a look into the issue I opened yesterday, cause I run into the same problem. I solved it by casting the x0:y0:x1:y1 as int() in python ;)

-> https://github.com/gregdavill/kicadScripts/issues/17

**Comment by gregdavill** [comment]
Is there still an issue running these scripts? 
I'll close this issue, but feel free to re-open or create a new issue if you encounter any issues.
